### ISSUE TITLE
parallel mode does not work with tif images

### ISSUE THREAD

**Issue by espenaf** [paolobenve/photofloat#27] opened 2017-07-06 05:48 UTC
I thumbnail_generation_mode=parallel, thumnails of tif images are reported as currupt like this: 

```
2017-07-06T07:40:33.525596   |  |  |  |--[ processing image/video]                 1999104.tif

2017-07-06T07:40:34.983790   |  |  |  |  |--[corrupt image]                           1999104.tif

2017-07-06T07:40:35.091845   |  |  |  |  |--[corrupt image]                           1999104.tif

2017-07-06T07:40:35.203525   |  |  |  |  |--[corrupt image]                           1999104.tif

2017-07-06T07:40:35.317236   |  |  |  |  |--[corrupt image]                           1999104.tif

2017-07-06T07:40:35.454228   |  |  |  |  |--[corrupt image]                           1999104.tif
```

Switching back to cascade makes thumbnail generation work as normal.

**Comment by jallakim** [comment] 2017-07-06 06:53
```parallel``` mode needs some love in general. It was something I wrote/did years ago, and isn't really *that* efficient in it's current state. My plan is to rewrite it completely, so that "mixed" can actually "prosper" (do N parallel threads, where N is "number of cores minus one", add all images for an album into the queue, and for each thread do cascade thumbnailing of all thumbnails for that particular image).

Why the corruptness, I don't know, but "cascade" is the fastest mode of all three of the modes, afaik, so just stick with "cascade" for now, unless you want to give it a go on fixing "parallel" mode (-:

**Comment by paolobenve** [comment] 2017-07-26 17:42
see https://en.wikipedia.org/wiki/Comparison_of_web_browsers#Image_format_support : very few browsers supports tiff. A note says:

> Although it was one of the first suggested WWW image formats, most browsers support TIFF by using a plugin installed by the user instead of decoding it natively.

**Comment by jallakim** [comment] 2017-07-26 18:13
> very few browsers supports tiff

Not really relevant here, though. We could still make "thumbnails" (the actual images used when browsing the album), which would all be JPEG. The bad support for TIFF would only affect the "original" link for each image; if the browser doesn't support viewing TIFF, you can still download the file and open it in whatever application you want.

**Comment by paolobenve** [comment] 2017-07-26 20:24
anyway, it seems that the problem with tiff is in the browsers, closing

**Closed by paolobenve** 2017-07-26 20:24 UTC
Labels: bug

**Comment by jallakim** [comment] 2017-07-26 21:34
Not really, the problem is with the thumbing (that, or the TIF-file @espenaf had is actually "corrupt").
